
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./_docker/Dockerfile
    working_dir: /workspace/src
    volumes:
      - ./src:/workspace/src
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - go_network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - go_network

networks:
  go_network:
    driver: bridge

volumes:
  mysql_data:
