
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./_docker/Dockerfile
    working_dir: /workspace/src
    volumes:
      - ./src:/workspace/src
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - go_network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - go_network

  migrate:
    container_name: migrate
    build:
      context: .
      dockerfile: ./_docker/Dockerfile.migrate
    volumes:
      - ./src:/workspace/src
    depends_on:
      - mysql
    networks:
      - go_network
    entrypoint: [
      "migrate", 
      "-path", "/workspace/src/db/migrations", 
      "-database", "mysql://root:${DB_PASSWORD}@tcp(mysql:3306)/${DB_NAME}", 
      "up"
    ]

  rollback:
    container_name: rollback
    build:
      context: .
      dockerfile: ./_docker/Dockerfile.migrate
    volumes:
      - ./src:/workspace/src
    depends_on:
      - mysql
    networks:
      - go_network
    entrypoint: [
      "migrate", 
      "-path", "/workspace/src/db/migrations", 
      "-database", "mysql://root:${DB_PASSWORD}@tcp(mysql:3306)/${DB_NAME}", 
      "down"
    ]

networks:
  go_network:
    driver: bridge

volumes:
  mysql_data:
